# Generated by Django 2.2.7 on 2019-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100, null=True)),
                ('year', models.DateTimeField()),
            ],
        ),
    ]
