# Generated by Django 2.2.7 on 2019-11-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191110_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='songs/image.png', upload_to='songs/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>'),
        ),
    ]
