# Generated by Django 2.2.7 on 2019-11-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='songs/image.png', upload_to='songs/'),
        ),
    ]
